{
 "title": "EdgeRouter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "router",
    "query": "show tag values from SystemStats with key=~/.*/"
   },
   {
    "name": "WAN",
    "query": "show tag values from Interfaces with key=~/ifname/"
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Transfer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Downloads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Interfaces",
     "query": "Select cumulative_sum(nnd_rx_bytes) FROM ( SELECT non_negative_difference(first(\"rx_bytes\")) AS \"nnd_rx_bytes\" FROM \"edgeos\".\"autogen\".\"Interfaces\" WHERE $timeFilter AND \"ifname\"=~/^$WAN$/ AND (\"router\" =~ /^$router$/) AND $timeFilter GROUP BY time($__interval) )",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "Uploads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Interfaces",
     "query": "Select cumulative_sum(nnd_tx_bytes) FROM ( SELECT non_negative_difference(first(\"tx_bytes\")) AS \"nnd_tx_bytes\" FROM \"edgeos\".\"autogen\".\"Interfaces\" WHERE $timeFilter AND \"ifname\"=~/^$WAN$/ AND (\"router\" =~ /^$router$/) AND $timeFilter GROUP BY time($__interval) )",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_user_type count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user_type" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Users",
     "query": "SELECT mean(\"count\") FROM \"Users\" WHERE (\"router\" =~ /^$router$/) AND $timeFilter GROUP BY time($__interval), \"user_type\" fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "Active hosts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Clients",
     "select": [
      [
       { "params": [ "num_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemStats",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "mem",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemStats",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    }
   ]
  },
  {
   "title": "DPI DATA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "download $tag_dpi by $tag_client_name/$tag_client_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dpi" ], "type": "tag" },
      { "params": [ "client_id" ], "type": "tag" },
      { "params": [ "client_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "DPI",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "8s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "upload $tag_dpi by $tag_client_name/$tag_client_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dpi" ], "type": "tag" },
      { "params": [ "client_id" ], "type": "tag" },
      { "params": [ "client_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "DPI",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "8s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    }
   ]
  },
  {
   "title": "$WAN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download $WAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interfaces",
     "query": "SELECT non_negative_difference(first(\"rx_bytes\")) FROM \"Interfaces\" WHERE (\"ifname\" = 'eth0' AND \"router\" = 'dumont.milosmeadow.com') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "8s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ifname", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "Upload $WAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interfaces",
     "query": "SELECT non_negative_difference(first(\"rx_bytes\")) FROM \"Interfaces\" WHERE (\"ifname\" = 'eth0' AND \"router\" = 'dumont.milosmeadow.com') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "8s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ifname", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "Latency $tag_target 95%",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "target" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    },
    {
     "alias": "Latency $tag_target 30m avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "target" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Latency",
     "query": "SELECT mean(\"latency\") FROM \"Latency\" WHERE (\"router\" =~ /^$router$/) AND $timeFilter GROUP BY time(1h), \"target\" fill(linear)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    }
   ]
  }
 ]
}